# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_2(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1003, 683)
        Dialog.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"color: rgb(255, 255, 255);")
        self.tbw_draw = QtWidgets.QTableWidget(Dialog)
        self.tbw_draw.setGeometry(QtCore.QRect(10, 10, 980, 601))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.tbw_draw.setFont(font)
        self.tbw_draw.setStyleSheet("background-color: rgb(54, 54, 54);\n"
"color: rgb(255, 255, 255);")
        self.tbw_draw.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tbw_draw.setObjectName("tbw_draw")
        self.tbw_draw.setColumnCount(0)
        self.tbw_draw.setRowCount(0)
        self.btn_ok = QtWidgets.QPushButton(Dialog)
        self.btn_ok.setGeometry(QtCore.QRect(910, 620, 80, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.btn_ok.setFont(font)
        self.btn_ok.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ok.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(64, 65, 66);")
        self.btn_ok.setObjectName("btn_ok")
        self.lab_description = QtWidgets.QLabel(Dialog)
        self.lab_description.setGeometry(QtCore.QRect(10, 650, 991, 25))
        self.lab_description.setMinimumSize(QtCore.QSize(0, 25))
        self.lab_description.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lab_description.setFont(font)
        self.lab_description.setText("")
        self.lab_description.setObjectName("lab_description")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_ok.setText(_translate("Dialog", "确定"))
