# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\pyqt5\project_developing\detail_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 500)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        Dialog.setFont(font)
        Dialog.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.titleLb = QtWidgets.QLabel(Dialog)
        self.titleLb.setGeometry(QtCore.QRect(10, 10, 750, 60))
        self.titleLb.setMinimumSize(QtCore.QSize(750, 60))
        self.titleLb.setMaximumSize(QtCore.QSize(750, 60))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.titleLb.setFont(font)
        self.titleLb.setStyleSheet("color: rgb(255, 255, 255);")
        self.titleLb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.titleLb.setObjectName("titleLb")
        self.btn_close = QtWidgets.QPushButton(Dialog)
        self.btn_close.setGeometry(QtCore.QRect(770, 0, 30, 30))
        self.btn_close.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_close.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_close.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(217, 0, 0);")
        self.btn_close.setObjectName("btn_close")
        self.tbw_info = QtWidgets.QTableWidget(Dialog)
        self.tbw_info.setGeometry(QtCore.QRect(20, 80, 761, 361))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.tbw_info.setFont(font)
        self.tbw_info.setStyleSheet("color: rgb(255, 255, 255);")
        self.tbw_info.setObjectName("tbw_info")
        self.tbw_info.setColumnCount(0)
        self.tbw_info.setRowCount(0)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(220, 450, 336, 34))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnOk = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.btnOk.setFont(font)
        self.btnOk.setStyleSheet("color: rgb(255, 255, 255);")
        self.btnOk.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.btnOk.setObjectName("btnOk")
        self.horizontalLayout.addWidget(self.btnOk)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnModi = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.btnModi.setFont(font)
        self.btnModi.setStyleSheet("color: rgb(255, 255, 255);")
        self.btnModi.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.btnModi.setObjectName("btnModi")
        self.horizontalLayout.addWidget(self.btnModi)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.titleLb.setText(_translate("Dialog", "TextLabel"))
        self.btn_close.setText(_translate("Dialog", "×"))
        self.btnOk.setText(_translate("Dialog", "确定"))
        self.btnModi.setText(_translate("Dialog", "修正"))
